# create a docker-compose.yml file
version: "3"
services:
  web:
    build: .
    #image: lk:latest
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    links:
      - db:db
    env_file:
      - lk_credentials.env
#    environment:
#      - LK_URL=$a${LK_URL}
#      - LK_USERNAME=$${LK_USERNAME}
#      - LK_PASSWORD=$${LK_PASSWORD}

  db:
      image: mysql
      container_name: test-mysql
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=secret2
        - MYSQL_DATABASE=helge

